//packers and movers
export {default as Home} from './screens/Home';
export {default as Orders} from './screens/Orders';
export {default as Bottomtab} from './Bottomtab/Bottomtab';
export {default as Location} from './screens/Location';
export {default as Droplocation} from './screens/Droplocation';
export {default as Droplocationsearch} from './screens/Droplocationsearch';
export {default as Picklocationsearch} from './screens/Pickuplocationsearch';
export {default as Pickuplocation} from './screens/Pickuplocation';
export {default as Servicedetails} from './screens/Servicedetails';
export {default as Booking} from './screens/Booking';
export {default as CCAvenuePayment} from './screens/CCAvenuePayment';
export {default as VehicleMovers} from './screens/VehicleMovers';
export {default as Viewdetails} from './screens/Viewdetails';
export {default as TermsAndConditions} from './screens/TermsandCondition';
export {default as Successful} from './screens/Successful';
export {default as OrderTab} from './screens/OrderTab';
export {default as PMEnquirydetails} from './screens/PMEnquirydetails';
export {default as PMVideo} from './screens/PMVideo';
